services:
  - type: web
    name: afterdark-birmingham
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: AFTERDARK_SECRET
        generateValue: true
      - key: AFTERDARK_ADMIN_EMAIL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
